name: bump brew formula

on:
  push:
    tags:
      - "v*"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.TOKEN }}
          tap: bartekpacia/homebrew-tools
          formula: scripts
          force: true
