name: prepare

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true

      - name: Verify code formatting
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          shfmt --list --diff ./bin/* || exit 1

      - name: Run linter
        run: |
          sudo apt install shellcheck
          shellcheck ./bin/* || exit 1
